### ISSUE TITLE
[BUG] Panic on send data to influx after create a new instance

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#181]
After creating a new instance , of the snmcollector the collector crashes
`````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x94f85

goroutine 275 [running]:
github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).addDataPoint(0xc4201cb030, 0xc4201dcd10)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:136 +0x77
github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).reportRuntimeStats(0xc4201cb030, 0x1236ac0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:260 +0x947
created by github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:182 +0xf6

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x94f857]

goroutine 275 [running]:
github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).addDataPoint(0xc4201cb030, 0xc4201dcd10)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:136 +0x77
github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).reportRuntimeStats(0xc4201cb030, 0x1236ac0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:260 +0x947
created by github.com/toni-moreno/snmpcollector/pkg/agent/selfmon.(*SelfMon).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/selfmon/selfmon.go:182 +0xf6
`````

Another error after deactivating selfmon

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x957040]

goroutine 503 [running]:
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).measConcurrentGatherAndSend.func1(0xc421e629f0, 0xc42044b0e0, 0xc421e629e0, 0xc421e629e8, 0xc4201ac9a0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/measgather.go:38 +0x1b0
created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).measConcurrentGatherAndSend
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/measgather.go:42 +0x15d
````

**Comment by toni-moreno** [comment]
we have found that last xorm update is creating precision 's' as 'S'  related to the iisue in  https://github.com/go-xorm/xorm/issues/572
