### ISSUE TITLE
[Bug] snmpcollector won't start after adding a specific measurement

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#243]
2017-06-20T20:33:40.520800+00:00 msr-infr-snmp01 systemd: Started SnmpCollector Agent.
2017-06-20T20:33:40.521259+00:00 msr-infr-snmp01 systemd: Starting SnmpCollector Agent...
2017-06-20T20:33:40.543958+00:00 msr-infr-snmp01 journal: Suppressed 802 messages from /system.slice/snmpcollector.service
2017-06-20T20:33:40.544485+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Set Default directories :
2017-06-20T20:33:40.544878+00:00 msr-infr-snmp01 snmpcollector: - Exec:
2017-06-20T20:33:40.545253+00:00 msr-infr-snmp01 snmpcollector: - Config: /etc/snmpcollector
2017-06-20T20:33:40.545637+00:00 msr-infr-snmp01 snmpcollector: -Logs: /var/log/snmpcollector
2017-06-20T20:33:40.546051+00:00 msr-infr-snmp01 snmpcollector: -Home:
2017-06-20T20:33:40.546384+00:00 msr-infr-snmp01 snmpcollector: "
2017-06-20T20:33:40.654012+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Initializing influxdb with id = [ default ]"
2017-06-20T20:33:40.654466+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Connecting to: 10.129.58.11"
2017-06-20T20:33:40.657499+00:00 msr-infr-snmp01 influxd: [httpd] 10.129.10.95,10.129.58.53 - snmpcollector [20/Jun/2017:20:33:40 +0000] "GET /ping?wait_for_leader=30s HTTP/1.1" 204 0 "-" "snmpcollector" beece22b-55f7-11e7-800e-000000000000 117
2017-06-20T20:33:40.659037+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Connected to: 10.129.58.11"
2017-06-20T20:33:40.659596+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Self monitoring TAGS inheritance set to : true"
2017-06-20T20:33:40.659998+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="SELFMON enabled {Enabled:true Freq:60 Prefix: InheritDeviceTags:true ExtraTags:[instance=snmpcollector01]}"
2017-06-20T20:33:40.660457+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: netscaler_vserver "
2017-06-20T20:33:40.660888+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: bgp_prefix "
2017-06-20T20:33:40.661258+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: switch_temperature "
2017-06-20T20:33:40.661710+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: ciscoMemoryPool "
2017-06-20T20:33:40.662094+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: ns_memoryusage "
2017-06-20T20:33:40.662445+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: network_32bits "
2017-06-20T20:33:40.662831+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: bgp_state "
2017-06-20T20:33:40.663532+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: ns_cpu_table "
2017-06-20T20:33:40.663919+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: fgt "
2017-06-20T20:33:40.664316+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: ipsla "
2017-06-20T20:33:40.664747+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: cpu "
2017-06-20T20:33:40.665129+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: nx_psu_index "
2017-06-20T20:33:40.665489+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: fgt_vdom "
2017-06-20T20:33:40.665889+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: fgt_sensorindex "
2017-06-20T20:33:40.666242+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: bfd "
2017-06-20T20:33:40.666712+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: netscaler_cspolicy "
2017-06-20T20:33:40.667146+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: ns_servicegroup "
2017-06-20T20:33:40.667476+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="processing measurement key: nexusCPUMem "
2017-06-20T20:33:40.668082+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="beggining Influx Sender thread: [default]"
2017-06-20T20:33:40.668675+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.669278+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.669864+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="SELFMON: Beginning  selfmonitor process for device"
2017-06-20T20:33:40.670493+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.671043+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.671532+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.672174+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.672758+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.673467+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.674108+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.674705+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.675294+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.675823+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.676364+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.676892+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.677540+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.678097+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already started (skipping Goroutine creation)"
2017-06-20T20:33:40.678664+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Sender thread to : default  already Initialized (skipping Initialization)"
2017-06-20T20:33:40.796462+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="setting HTML Static Path to public"
2017-06-20T20:33:40.796690+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:40" level=info msg="Server is running on localhost:8090..."
2017-06-20T20:33:41.849358+00:00 msr-infr-snmp01 snmpcollector: panic: runtime error: index out of range
2017-06-20T20:33:41.849785+00:00 msr-infr-snmp01 snmpcollector: goroutine 435 [running]:
2017-06-20T20:33:41.850137+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.sectionDotSlice(0xc4240edf5a, 0x2a, 0x6, 0xa, 0x0, 0x3)
2017-06-20T20:33:41.850466+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/formatindextag.go:83 +0x15c
2017-06-20T20:33:41.850822+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.formatTag(0xc4203ba690, 0xc4202a8e60, 0x15, 0xc4215344e0, 0xbdafa3, 0x4, 0xc428988340, 0xc42028e360)
2017-06-20T20:33:41.851152+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/formatindextag.go:157 +0x117e
2017-06-20T20:33:41.851442+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).loadIndexedLabels(0xc4279a8840, 0xbebba2, 0x16, 0x0)
2017-06-20T20:33:41.851778+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:532 +0x3fe
2017-06-20T20:33:41.852102+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).Init(0xc4279a8840, 0xc4279a8840, 0xc424623b58)
2017-06-20T20:33:41.852394+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:101 +0x271
2017-06-20T20:33:41.852895+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.New(0xc4202a65a0, 0xc4203ba690, 0xc424cbed20, 0xc424623c00, 0xc424cbed20, 0x0, 0x0)
2017-06-20T20:33:41.853291+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:60 +0xe2
2017-06-20T20:33:41.853621+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc4203ac6c0)
2017-06-20T20:33:41.853920+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:237 +0xb8f
2017-06-20T20:33:41.854353+00:00 msr-infr-snmp01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc4203ac6c0, 0x1177d40)
2017-06-20T20:33:41.854710+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:467 +0x2fe
2017-06-20T20:33:41.855056+00:00 msr-infr-snmp01 snmpcollector: created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
2017-06-20T20:33:41.855391+00:00 msr-infr-snmp01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:435 +0x60
2017-06-20T20:33:41.896273+00:00 msr-infr-snmp01 systemd: snmpcollector.service: main process exited, code=exited, status=2/INVALIDARGUMENT
2017-06-20T20:33:41.896756+00:00 msr-infr-snmp01 systemd: Unit snmpcollector.service entered failed state.
2017-06-20T20:33:41.897164+00:00 msr-infr-snmp01 systemd: snmpcollector.service failed.
2017-06-20T20:33:42.023038+00:00 msr-infr-snmp01 systemd: snmpcollector.service holdoff time over, scheduling restart.

The measurement that I added.: 

2017-06-20T20:33:42.135795+00:00 msr-infr-snmp01 snmpcollector: time="2017-06-20 20:33:42" level=info msg="processing measurement key: bfd "

However, I can't seem to find this in influxdb to delete it. 

Any ideas?

**Comment by toni-moreno** [comment]
Hi @Smenon10 , Thank you to report this bug, I will review ASAP.

In the meanwhile I suggest you delete the measurement that causes this error in the sqlite db 

``` 
sqlite3 snmpcollector.db
#delete from measurement_cfg where id = 'XXXXXX'
````

**Comment by gradew** [comment]
Hi @toni-moreno,

Thank you for your quick reply. Your suggestion worked :)

Cheers,
Julien

**Comment by toni-moreno** [comment]
Hi  Julien , can you show us your snmpcollector version  ?

````
./bin/snmpcollector -version
````
Thx

**Comment by gradew** [comment]
Hi Toni,

snmpcollector v0.7.2 (git: 2338668 ) built at [2017-05-27 04:19:04]

Thx :)

**Comment by toni-moreno** [comment]
Could you remember the measurement configuration that has caused the crash?

Could you reproduce the crash ( in a testing instance) and  send/show us the  the device log  where you added the measurement?

**Comment by Smenon10** [comment]
I remember I was trying to add a influx measurement

in the transformation part, I set it to ${IDX1|DOT[0:3]|ALL}, tested that it didn't give me the info I needed. I tried ${IDX1|DOT[6:10]|ALL} then it crash looped. It might've been possible that there was no 6:10, as in, there was no 10th "." and that caused the crash loop.

**Comment by toni-moreno** [comment]
Can you show me an example of the 
Queried OID with its base and index part? What exactly did you need to do?

**Comment by Smenon10** [comment]
index: .1.3.6.1.4.1.9.10.137.1.4.1.1
base: .1.3.6.1.4.1.9.10.137.1.2.1.6

For the index, it gives us a value like 

SNMPv2-SMI::enterprises.9.10.137.1.4.1.1.1090519321.1090519081.1.4.10.129.0.84 = Gauge32: 1090519081

Using ${IDX1|DOT[6:10]|ALL} -> I was trying to use grab 10.129.0.84

I can see now the above wouldn't have worked regardless, but I don't think it should've caused a process issue.

**Comment by toni-moreno** [comment]
Hi @Smenon10 , I've fix a couple of bugs related with first and second index in the DOT[first:second] parameters. I  hope you can test again when next 0.7.3 version will be released ( in a few days)
Thank you very much

**Comment by toni-moreno** [comment]
Hi @Smenon10 , the new 0.7.3 release has been released.
