### ISSUE TITLE
JavaScript errors in Frontend

### ISSUE THREAD

**Issue by jamesboswell** [toni-moreno/snmpcollector#28]
Chrome console is reporting the following JS errors.   Same install and environment as #27 

```javascript
Uncaught ReferenceError: System is not defined
    at http://localhost:3002/systemjs.config.js:6:3
    at http://localhost:3002/systemjs.config.js:56:3

Uncaught ReferenceError: System is not defined
    at http://localhost:3002/:23:9
```

All for `System` not being defined

**Comment by toni-moreno** [comment]
read  https://github.com/toni-moreno/snmpcollector/issues/27 before continue! :)

**Comment by jamesboswell** [comment]
Closing in favor of #27
