### ISSUE TITLE
[Bug] Service crashes and unable to start after binding metric to a measurement.

### ISSUE THREAD

**Issue by jchristopher327** [toni-moreno/snmpcollector#285]
Please include this information:
- What SnmpCollector version are you using?
```
[root@nemetrics01 administrator]# snmpcollector --version
snmpcollector v0.7.4 (git: 304bb8d ) built at [2017-09-23 00:23:30]
```
- What OS are you running snmpcollector on?
```
[root@nemetrics01 administrator]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
```
- What did you do?
I added a new metric and tied it to an indexed measurement which it didnt belong to. Once I reloaded the config, the service crashed and is unable to start.
I tried to follow the instructions on issue #243 but I get the following error:

```
sqlite> delete from measurement_cfg where id = 'F5_VIPs'
   ...> ;
Error: no such table: measurement_cfg
```

What I'd like to do is delete the newly created metric but haven't found a way of doing that. When I run `.tables.` I see nothing coming back.

```
sqlite> .tables
sqlite>
```

**Comment by toni-moreno** [comment]
Hi @jchristopher327  the best way is delete the relation between metric and measurement in the 'measurement_field_cfg' table.
check first the config still exist.

````sql
select * from measurement_field_cfg where id_measurement_cfg = '<your_measurment_id>'
````
after that you can delete the wrong metric 

````sql
delete from measurement_field_cfg  where id_metric_cfg = '<your_wrong_metric>' and id_measurement_cfg = '<your_measurment_id>'
````
After the workaround done , I suggest you to send me the panic trace and logs to investigate the origin of this problem.

**Comment by jchristopher327** [comment]
Hi @toni-moreno,

```
sqlite> select * from measurement_field_cfg where id_measurement_cfg = 'F5_VIPs';
Error: no such table: measurement_field_cfg
```
Just looks like there's nothing there unfortunately. 

Regarding the logs and traces, I don't see an `snmpcollectopr.log` file under the `/var/log/snmpcolector/` directory. I have `logLevel = "debug"` configured as well.

**Comment by toni-moreno** [comment]
hi  @jchristopher327  did you execute sqlite on the db file?
````bash
sqlite3 /var/lib/snmpcollector/snmpcollector.db 
````
I'm not sure where the db file is located in CentOS but I think is in /var/lib/snmpcollector/snmpcollector.db

**Comment by jchristopher327** [comment]
Thanks, I was able to delete the relation between the metric and measurement. However, that didn't look to the be issue (or maybe part of the issue) as the service would still fail. There are some other metrics that I set up prior to me reloading the config. One of them was `ltmVirtualServAddr|ltmVirtualServAddr||.1.3.6.1.4.1.3375.2.2.10.1.2.1.3|IpAddress|0|0.0|0.0|0|` which the devices returns as `Hex-STRING` but that didn't look like an option in snmpcollector. Some documentation showed that the value was an IP address so figured I'd try that and see what happens.

Once I deleted that metric I was able to restart the service. Like I previously mentioned I don't have an `snmpcollector.log` file for some reason so not sure what else I can provide. 

Thanks for the help as always and feel free to close the issue.

**Comment by toni-moreno** [comment]
Not yet!! @jchristopher327 

I need the panic generated somewhere in your system to fix the origin of the crash (the agent should detect any misconfiguration and log it , but not crash!)  

Can you check if there is the panic trace somewhere in /var/log/snmpcollector/* /var/log/messages* or   /run/log/journal/* or /var/log/journal/*

Thank you !

**Comment by jchristopher327** [comment]
I found the following `panic` references under `/var/log/messages`

```
Nov 28 14:36:33 nemetrics01 snmpcollector: time="2017-11-28 14:36:33" level=warning msg="Error on insert Measurement F5_VIPs  , affected : 0 , error: No Fields added to measurement F5_VIPs"
Nov 28 14:40:19 nemetrics01 snmpcollector: time="2017-11-28 14:40:19" level=warning msg="We're missing some gc pause times"
Nov 28 14:48:58 nemetrics01 snmpcollector: time="2017-11-28 14:48:58" level=warning msg="We're missing some gc pause times"
Nov 28 14:50:18 nemetrics01 snmpcollector: time="2017-11-28 14:50:18" level=warning msg="We're missing some gc pause times"
Nov 29 09:00:16 nemetrics01 snmpcollector: time="2017-11-29 09:00:16" level=warning msg="We're missing some gc pause times"
Nov 29 09:05:59 nemetrics01 snmpcollector: time="2017-11-29 09:05:59" level=warning msg="We're missing some gc pause times"
Nov 29 09:06:00 nemetrics01 snmpcollector: panic: interface conversion: interface {} is string, not []uint8
Nov 29 09:06:00 nemetrics01 snmpcollector: goroutine 287477 [running]:
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/snmp.PduVal2IPaddr(0xc420189320, 0x5e, 0x4, 0xafe380, 0xc4202f8e20, 0x113b760, 0xc4203be0a0, 0x30, 0xc420f25e00, 0x46, ...)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/snmp/snmp.go:452 +0x165
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/metric.(*SnmpMetric).Init.func20(0xc420189320, 0x5e, 0x4, 0xafe380, 0xc4202f8e20, 0x113b760, 0xc4203be0a0, 0xed1b0dff8, 0x142d808f, 0x11683c0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/metric/snmpmetric.go:333 +0x5b
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData.func1(0xc420189320, 0x5e, 0x4, 0xafe380, 0xc4202f8e20, 0x113b760, 0xc4203be0a0, 0x0, 0x0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:307 +0x2c2
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc420dcc1c0, 0xc420029ca5, 0xc420c3e4a0, 0x20, 0xc42056ef80, 0x0, 0x0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:80 +0x2bd
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc420dcc1c0, 0xc420c3e4a0, 0x20, 0xc42056ef80, 0x0, 0x0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:359 +0x4e
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk-fm(0xc420c3e4a0, 0x20, 0xc42056ef80, 0x0, 0x0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:89 +0x48
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData(0xc42029af00, 0xc420db00f0, 0xb06920, 0xc42019e6c0, 0xc42029af08, 0xc42019e6c0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:315 +0x1e1
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData-fm(0xc42029af00, 0xc0661f, 0x2d, 0xc420921b28, 0x1)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:82 +0x2a
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc4200d43c0)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:285 +0x11e2
Nov 29 09:06:00 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc4200d43c0, 0x1185640)
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:562 +0x305
Nov 29 09:06:00 nemetrics01 snmpcollector: created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
Nov 29 09:06:00 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:530 +0x60
Nov 29 09:06:01 nemetrics01 snmpcollector: panic: interface conversion: interface {} is string, not []uint8
Nov 29 09:06:01 nemetrics01 snmpcollector: goroutine 301 [running]:
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/snmp.PduVal2IPaddr(0xc4201ebf20, 0x5e, 0x4, 0xafe380, 0xc420947060, 0x113b760, 0xc4202603c0, 0x30, 0xc420f1c5a0, 0x46, ...)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/snmp/snmp.go:452 +0x165
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/metric.(*SnmpMetric).Init.func20(0xc4201ebf20, 0x5e, 0x4, 0xafe380, 0xc420947060, 0x113b760, 0xc4202603c0, 0xed1b0dff9, 0x2da9e975, 0x11683c0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/metric/snmpmetric.go:333 +0x5b
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData.func1(0xc4201ebf20, 0x5e, 0x4, 0xafe380, 0xc420947060, 0x113b760, 0xc4202603c0, 0x0, 0x0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:307 +0x2c2
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc4201c0620, 0xc420028ca5, 0xc4202c6440, 0x20, 0xc420876680, 0x0, 0x0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:80 +0x2bd
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc4201c0620, 0xc4202c6440, 0x20, 0xc420876680, 0x0, 0x0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:359 +0x4e
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk-fm(0xc4202c6440, 0x20, 0xc420876680, 0x0, 0x0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:89 +0x48
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData(0xc4209f4840, 0xc4202922a0, 0xb06920, 0xc4206198f0, 0xc4209f4848, 0xc4206198f0)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:315 +0x1e1
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData-fm(0xc4209f4840, 0xc0661f, 0x2d, 0xc42042fb28, 0x1)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:82 +0x2a
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc420173040)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:285 +0x11e2
Nov 29 09:06:01 nemetrics01 snmpcollector: github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc420173040, 0x1185640)
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:562 +0x305
Nov 29 09:06:01 nemetrics01 snmpcollector: created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
Nov 29 09:06:01 nemetrics01 snmpcollector: /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:530 +0x60
Nov 29 09:06:03 nemetrics01 snmpcollector: panic: interface conversion: interface {} is string, not []uint8
```

**Comment by toni-moreno** [comment]
This is the error
`panic: interface conversion: interface {} is string, not []uint8`

And this is the code that causes it
````golang
	switch vt := value.(type) {
	case string:
		ipbs = []byte(vt)
		return string(ipbs), nil
	case []byte:
		ipbs = vt
		switch len(ipbs) {
		case 4, 16:
			value = net.IP(ipbs).String()
		default:
			return "", fmt.Errorf("invalid length (%d) for ipaddr conversion", len(ipbs))
		}
		return string(value.([]byte)), nil //This line causes the panic
	default:
		return "", fmt.Errorf("invalid type (%T) for ipaddr conversion", value)
	}
````

**Comment by toni-moreno** [comment]
Hi @jamesboswell thank you very much for your report, I've fixed a bug in this piece of the code.
