### ISSUE TITLE
TypeError in ValidationService.OIDValidator,  UI lockup

### ISSUE THREAD

**Issue by jamesboswell** [toni-moreno/snmpcollector#30]
### What:
Reset form action in SNMP metrics form throws a TypeError.  Second reset of form locks up the entire UI.  All buttons and left side menu become unresponsive.

### Version 
SNMPCollector - 0.5.3 - ff26b4b (Nov 7, 2016)
### Steps to reproduce:

1. Login
2. Select **SNMP metrics**
3. Select **Add metric**
4. Select **DataSrcType Integer** *(any of them really)*
5. Click **Reset**  (at this point you will get error below)
6. Fill in the form again
7. Click **Reset** again (now the entire UI will lockup including left-side menu)

````
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
id_token: OK
check canActivate:
creating home!! id_token:OK
Task Service created. Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
Task Service created. Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
Task Service created. Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
Task Service created. Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
MAP SERVICE null
DONE
Task Service created. Http {_backend: XHRBackend, _defaultOptions: BaseRequestOptions}
MAP SERVICE [Object]
FOREACH LOOP Object {ID: "1", FieldName: "ifHCInOctets", Description: "ifHCInOctets", BaseOID: ".1.3.6.1.2.1.31.1.1.1.6", DataSrcType: "COUNTER64"…} 1
DONE
EXCEPTION: Error in public/snmpmetric/snmpmetriceditor.html:41:4 caused by: Cannot read property 'match' of null
ORIGINAL EXCEPTION: Cannot read property 'match' of null
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'match' of null
    at ValidationService.OIDValidator (http://localhost:8090/public/common/validation.service.js:52:38)
    at eval (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:658:53)
    at Array.map (native)
    at _executeValidators (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:658:27)
    at eval (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:638:37)
    at eval (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:658:53)
    at Array.map (native)
    at _executeValidators (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:658:27)
    at FormControl.eval [as validator] (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:638:37)
    at FormControl.AbstractControl._runValidator (http://localhost:8090/node_modules/@angular/forms/bundles/forms.umd.js:2203:53)
ERROR CONTEXT:
DebugContext {_view: _View_SnmpMetricCfgComponent5, _nodeIndex: 1, _tplRow: 41, _tplCol: 4}
Uncaught ViewWrappedError {_nativeError: Error: Error in public/snmpmetric/snmpmetriceditor.html:41:4 caused by: Cannot read property 'match'…, originalError: TypeError: Cannot read property 'match' of null
    at ValidationService.OIDValidator (http://localh…, context: DebugContext}
```

**Comment by sbengo** [comment]
Thanks for reporting this @jamesboswell, fixed with merged PR #34 
Can we close this issue?

Regards!

**Comment by toni-moreno** [comment]
Hi @jamesboswell , I've closed this issue. 

you can  reopen  it if the error still persist. Thank you !

**Comment by jamesboswell** [comment]
@sbengo  @toni-moreno  thank you both.  confirmed this bug is fixed
