### ISSUE TITLE
PANIC: on load last version

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#376]
On two differents instalations some config is doing a panic. Pending check

````bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9512ec]

goroutine 236 [running]:
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData.func1(0xc0003b1280, 0x1a, 0x4, 0xb84480, 0xc000488400, 0xd46360, 0xc00001f8b0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:316 +0x29c
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc0004a21c0, 0xc0000707a5, 0xc0002cf820, 0x18, 0xc000475dc0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:80 +0x278
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc0004a21c0, 0xc0002cf820, 0x18, 0xc000475dc0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:359 +0x4e
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk-fm(0xc0002cf820, 0x18, 0xc000475dc0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:89 +0x48
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData(0xc0001b0410, 0xc000c51f80, 0xc000dbc420, 0x1, 0xc000343480, 0x1b)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:324 +0x1c5
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData-fm(0xc0001b0410, 0xc00018fc20, 0x0, 0x0, 0x2)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:82 +0x2a
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc000464b00)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:305 +0xaed
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).gatherAndProcessData(0xc000464b00, 0xc000328500, 0x0, 0xc00073df10)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:631 +0x116
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc000464b00, 0x144f508)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:732 +0xdea
created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:708 +0x60
````
Here Another log

````bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9512ec]

goroutine 226 [running]:
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData.func1(0xc0003ed5a0, 0x1a, 0x4, 0xb84480, 0xc0005643a0, 0xd46360, 0xc0001c9360, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:316 +0x29c
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc000c1a700, 0xc00006e7a5, 0xc0002b5f60, 0x18, 0xc0010483c0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:80 +0x278
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc000c1a700, 0xc0002b5f60, 0x18, 0xc0010483c0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:359 +0x4e
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk-fm(0xc0002b5f60, 0x18, 0xc0010483c0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:89 +0x48
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData(0xc0001b3040, 0xc00114c330, 0xc00114c7b0, 0x0, 0xc000585ec0, 0x27)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:324 +0x1c5
github.com/toni-moreno/snmpcollector/pkg/data/measurement.(*Measurement).SnmpWalkData-fm(0xc0001b3040, 0xc0003c8ea0, 0x0, 0x0, 0x2)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/data/measurement/measurement.go:82 +0x2a
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).InitDevMeasurements(0xc000145600)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:305 +0xaed
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).gatherAndProcessData(0xc000145600, 0xc000404280, 0x0, 0xc0004d2f10)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:631 +0x116
github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).startGatherGo(0xc000145600, 0x144f508)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:732 +0xdea
created by github.com/toni-moreno/snmpcollector/pkg/agent/device.(*SnmpDevice).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/agent/device/snmpdevice.go:708 +0x60
````

**Comment by toni-moreno** [comment]
This panic is done by leak of previous database  upgrade.

Now OCTETSTRING metrics on upgrade takes by default Conversion=0 ( => to Float) and  should be Conversion = 3( STRING) 

From 0.8 we should execute this SQL sentence on the snmpcollector database.
````sql
update snmp_metric_cfg set Conversion=3 where datasrctype='OCTETSTRING';
````
