### ISSUE TITLE
Panic on reload Indexes

### ISSUE THREAD

**Issue by toni-moreno** [toni-moreno/snmpcollector#56]
```
goroutine 91 [running]:
panic(0xca2180, 0xc8200120f0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*InfluxMeasurement).loadIndexedLabels.func1(0xc821c25a80, 0x17, 0x41, 0xb7bc80, 0xc82197c838, 0x7f29e16272f8, 0xc820488140, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/influxmeasurement.go:604 +0xaaf
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).getToWalk(0xc8200e42a0, 0xc8201e4440, 0x1e, 0xc82172a800, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:106 +0x20e
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).walk(0xc8200e42a0, 0xc821d198a5, 0xc8201e4440, 0x1e, 0xc82172a800, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/walk.go:69 +0x74f
github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp.(*GoSNMP).BulkWalk(0xc8200e42a0, 0xc8201e4440, 0x1e, 0xc82172a800, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/vendor/github.com/soniah/gosnmp/gosnmp.go:355 +0x50
main.(*InfluxMeasurement).loadIndexedLabels(0xc820e66200, 0xe25ea0, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/influxmeasurement.go:632 +0x3a6
main.(*InfluxMeasurement).UpdateFilter(0xc820e66200, 0xc82ae53e4f, 0x0, 0x0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/influxmeasurement.go:274 +0x316
main.(*SnmpDevice).startGatherGo(0xc82047b130, 0x13ce8f0)
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/snmpdevice.go:398 +0x20f7
created by main.(*SnmpDevice).StartGather
        /home/developer/src/gospace/src/github.com/toni-moreno/snmpcollector/pkg/snmpdevice.go:348 +0x3f
 ```

**Comment by toni-moreno** [comment]
This bug has been inserted  in  https://github.com/toni-moreno/snmpcollector/commit/ae213c24d50a649afd1db726c55d812b15806e1c, now we need some extra check for erroneus pdu names. ( it happens when remote device is not returning us data )
